### ISSUE TITLE
How to know which memory address should patch 

### ISSUE THREAD

**Issue by Jecvay** [kh0nsu/FromStutterFix#1]
And what value should patch in mem

I want to find what device cause the refresh to device manager

is there a way to print the device related?

thanks a lot

**Comment by kh0nsu** [comment]
First off:

> is there a way to print the device related?

I'm not entirely sure. You'd need to write code that asks Windows to inform you about device changes (this is what the game does) and just wait and see what you get. You can't do this with the game open as it only works for one window at a time.

There's some detail here: https://learn.microsoft.com/en-us/windows/win32/devio/wm-devicechange

There may be an existing tool that does this. Otherwise ChatGPT might be able to help.

As for which address is needed and how to patch it, this is a very in-depth topic and it's hard to provide much guidance on where to get started. Maybe look up guides for Cheat Engine as a starting point.

The thing you're looking for is a call to IDirectInput8::EnumDevices (this is the part the takes 100ms+ and lags your game), but be wary of steam: it can hook into the game and hijack this so the call looks like it's going somewhere else! Some detail here: https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ee417804(v=vs.85)

If you just need a fix for Elden Ring, DS3 or Sekiro, the updated fork has you covered: https://github.com/t0mtee/FromStutterFixUpdated

There are similar fixes for some other games if you know what to search for, plus some 'generic' fixes which, as far as I can tell, won't actually work for fromsoft games but might work for others. Try searching for things like:

- Device stutter fix
- DInput stutters
- DInput8 wrapper

Good luck!

**Comment by Jecvay** [comment]
Thank you very much for your answer. I tried writing code to monitor hardware changes, but couldn't pinpoint the issue. When stuttering occurred, there were no device changes indicated. Based on your suggestion, I rewrote a simple program using the wm-devicechange interface, but still didn't detect any issues. The article on EnumDevices is quite good; I saw that some people have identified their issues with sound drivers and similar areas. However, I disconnected all USB devices (except for the Xbox), even unplugged the keyboard and mouse, leaving only the monitor and Xbox controller. I even disconnected all motherboard connections to the case USB hub, but the problem remains unsolved. I guess I'll have to wait for an official fix. Strangely, I didn't encounter any stuttering in another game by FromSoftware, Armored Core 6. Disabling the Windows "allow your controller to open game bar" seems to have some effect for me. Thanks again for your help.
